### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by rozzzly** [WebReflection/safer-promise#1]
I see what your project does, but why would this be necessary? Neither your description nor code example explains/demonstrates what this is meant to protect against. So far as I can tell, this is just a wrapper arround Promise that gets frozen while keeping the native Promise prototype untouched (and unfrozen). Perhaps I'm just obtuse, but I don't see any practical use case of this package.

Could you please update the `README.md` to include a _real-world_ example showing the utility of this package?

**Comment by WebReflection** [comment]
> Perhaps I'm just obtuse, but I don't see any practical use case of this package.

import/require this on top of any other script, and try to interfere with anything it does ... even a console log in between to demonstrate you can intercept any value passed through promises.

Once you realize you can't, maybe close this issue? Otherwise please file a bug, thanks.

**Comment by rozzzly** [comment]
No, I get the the objective, to prevent hijacking of a promise. What I'm asking is **why**. Can you give an example where:

  1.  Somebody _**wants**_ to spy on/hijack your promise.

  2. You _**need**_ to prevent that.

Like a real world example. I understand what you're trying to do, I'm asking why you need to do so.

**Comment by WebReflection** [comment]
You have a real world attack example in [safer-crypto](https://github.com/WebReflection/safer-crypto#safer-crypto), since it's based on Promise API.

Is the ability to intercept in clear any password used to eventually encrypt or decrypt content, including the ability to intercept such content, good enough as use case?

**Comment by WebReflection** [comment]
P.S. also [safer-pass](https://github.com/WebReflection/safer-pass#readme) is based on both safer-crypto and safer-promise, among other safer things. Does this answer your question?

**Comment by rozzzly** [comment]
That's not an issue with promises being possible to monkey patch for nefarious purposes. The issue is you're relying on hackey abstractions over basic precautions to prevent XSS. 

You're treating the symptom, not the condition.

**Comment by WebReflection** [comment]
@rozzzly no, I work with web extensions and analyze daily sites that do literally everything they can to disrupt JS as we know it, so I have more than 99 reasons to use safer primitives whenever I need to ship code that I want both users, and myself, to always trust it.
